-- MySQL Script generated by MySQL Workbench
-- Mon Sep  5 18:17:11 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`CarteiraCliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`CarteiraCliente` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`CarteiraCliente` (
  `idCarteiraCliente` INT NOT NULL,
  `ApelidoCartao` VARCHAR(50) NOT NULL,
  `NumeroCartao` INT NOT NULL,
  `NomeTitular` VARCHAR(100) NOT NULL,
  `Validade` INT NOT NULL DEFAULT 'MesAno',
  `CPF_Titular` INT NULL DEFAULT Para cadastro do cartao de outra pessoa,
  `cliente_IdCliente` INT NOT NULL,
  `TipoCartao_idTipoCartao` INT NOT NULL,
  PRIMARY KEY (`idCarteiraCliente`, `cliente_IdCliente`, `TipoCartao_idTipoCartao`),
  CONSTRAINT `fk_CarteiraCliente_cliente1`
    FOREIGN KEY (`cliente_IdCliente`)
    REFERENCES `mydb`.`cliente` (`IdCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CarteiraCliente_TipoCartao1`
    FOREIGN KEY (`TipoCartao_idTipoCartao`)
    REFERENCES `mydb`.`TipoCartao` (`idTipoCartao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_CarteiraCliente_cliente1_idx` ON `mydb`.`CarteiraCliente` (`cliente_IdCliente` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `fk_CarteiraCliente_TipoCartao1_idx` ON `mydb`.`CarteiraCliente` (`TipoCartao_idTipoCartao` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`Dados_Entrega`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Dados_Entrega` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`Dados_Entrega` (
  `idDados_Entrega` INT NOT NULL,
  `Tipo_De_Entrega_idTipo_De_Entrega` INT NOT NULL,
  `TipoSituacao_idTipoSituacao` INT NOT NULL,
  `CodigoRastreio` VARCHAR(45) NULL,
  `Observacoes` VARCHAR(45) NULL,
  PRIMARY KEY (`idDados_Entrega`, `Tipo_De_Entrega_idTipo_De_Entrega`, `TipoSituacao_idTipoSituacao`),
  CONSTRAINT `fk_Dados_Entrega_Tipo_De_Entrega1`
    FOREIGN KEY (`Tipo_De_Entrega_idTipo_De_Entrega`)
    REFERENCES `mydb`.`Tipo_De_Entrega` (`idTipo_De_Entrega`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Dados_Entrega_TipoSituacao1`
    FOREIGN KEY (`TipoSituacao_idTipoSituacao`)
    REFERENCES `mydb`.`TipoSituacao` (`idTipoSituacao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_Dados_Entrega_Tipo_De_Entrega1_idx` ON `mydb`.`Dados_Entrega` (`Tipo_De_Entrega_idTipo_De_Entrega` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `fk_Dados_Entrega_TipoSituacao1_idx` ON `mydb`.`Dados_Entrega` (`TipoSituacao_idTipoSituacao` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`Dipobiliza_Produtos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Dipobiliza_Produtos` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`Dipobiliza_Produtos` (
  `Fornecedor_idFornecedor` INT NOT NULL,
  `Produto_IdProduto` INT NOT NULL,
  PRIMARY KEY (`Fornecedor_idFornecedor`, `Produto_IdProduto`),
  CONSTRAINT `fk_Fornecedor_has_Produto_Fornecedor`
    FOREIGN KEY (`Fornecedor_idFornecedor`)
    REFERENCES `mydb`.`Fornecedor` (`idFornecedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Fornecedor_has_Produto_Produto1`
    FOREIGN KEY (`Produto_IdProduto`)
    REFERENCES `mydb`.`Produto` (`IdProduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_Fornecedor_has_Produto_Produto1_idx` ON `mydb`.`Dipobiliza_Produtos` (`Produto_IdProduto` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `fk_Fornecedor_has_Produto_Fornecedor_idx` ON `mydb`.`Dipobiliza_Produtos` (`Fornecedor_idFornecedor` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`Estoque`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Estoque` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`Estoque` (
  `idEstoque` INT NOT NULL,
  `Local` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idEstoque`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`Fornecedor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Fornecedor` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`Fornecedor` (
  `idFornecedor` INT NOT NULL,
  `RazaoSocial` VARCHAR(45) NULL,
  `CNPJ` VARCHAR(14) NULL,
  `Fornecedorcol` VARCHAR(45) NULL,
  PRIMARY KEY (`idFornecedor`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`Pagamento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Pagamento` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`Pagamento` (
  `idPagamento` INT NOT NULL,
  `IdTipoPagamento` INT NULL,
  `Parcelas` INT NULL,
  `Primeiro_Vencimento` DATE NULL,
  `Ultimo_Vencimento` DATE NULL COMMENT 'Na camada de aplicacao calcular as datas intermediarias combinando o numero de parcelas com a primeira e ultima data de vencimento.',
  `TipoPagamento_idTipoPagamento` INT NOT NULL,
  PRIMARY KEY (`idPagamento`, `TipoPagamento_idTipoPagamento`),
  CONSTRAINT `fk_Pagamento_TipoPagamento1`
    FOREIGN KEY (`TipoPagamento_idTipoPagamento`)
    REFERENCES `mydb`.`TipoPagamento` (`idTipoPagamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_Pagamento_TipoPagamento1_idx` ON `mydb`.`Pagamento` (`TipoPagamento_idTipoPagamento` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`Produto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Produto` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`Produto` (
  `IdProduto` INT NOT NULL,
  `IdCategoria` INT NOT NULL,
  `Identificacao` VARCHAR(45) NULL,
  `Valor` VARCHAR(45) NOT NULL,
  `Descricao` VARCHAR(45) NULL,
  `IdFornecedor` INT NOT NULL,
  PRIMARY KEY (`IdProduto`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`Produto_em_Estoque`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Produto_em_Estoque` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`Produto_em_Estoque` (
  `Produto_IdProduto` INT NOT NULL,
  `Estoque_idEstoque` INT NOT NULL,
  `Quantidade` INT NOT NULL,
  PRIMARY KEY (`Produto_IdProduto`, `Estoque_idEstoque`),
  CONSTRAINT `fk_Produto_has_Estoque_Produto1`
    FOREIGN KEY (`Produto_IdProduto`)
    REFERENCES `mydb`.`Produto` (`IdProduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Produto_has_Estoque_Estoque1`
    FOREIGN KEY (`Estoque_idEstoque`)
    REFERENCES `mydb`.`Estoque` (`idEstoque`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_Produto_has_Estoque_Estoque1_idx` ON `mydb`.`Produto_em_Estoque` (`Estoque_idEstoque` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `fk_Produto_has_Estoque_Produto1_idx` ON `mydb`.`Produto_em_Estoque` (`Produto_IdProduto` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`Produtos_Por_Vendedor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Produtos_Por_Vendedor` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`Produtos_Por_Vendedor` (
  `Vendedor Agregado_idVendedor Agregado` INT NOT NULL,
  `Produto_IdProduto` INT NOT NULL,
  `Quantidade` INT NULL,
  PRIMARY KEY (`Vendedor Agregado_idVendedor Agregado`, `Produto_IdProduto`),
  CONSTRAINT `fk_Vendedor Agregado_has_Produto_Vendedor Agregado1`
    FOREIGN KEY (`Vendedor Agregado_idVendedor Agregado`)
    REFERENCES `mydb`.`Vendedor_Agregado` (`idVendedor Agregado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Vendedor Agregado_has_Produto_Produto1`
    FOREIGN KEY (`Produto_IdProduto`)
    REFERENCES `mydb`.`Produto` (`IdProduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_Vendedor Agregado_has_Produto_Produto1_idx` ON `mydb`.`Produtos_Por_Vendedor` (`Produto_IdProduto` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `fk_Vendedor Agregado_has_Produto_Vendedor Agregado1_idx` ON `mydb`.`Produtos_Por_Vendedor` (`Vendedor Agregado_idVendedor Agregado` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`Relacao_Produto_Pedido`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Relacao_Produto_Pedido` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`Relacao_Produto_Pedido` (
  `pedido_idPedido` INT NOT NULL,
  `Produto_IdProduto` INT NOT NULL,
  `Qunatidade` INT NULL,
  `Relacao_Produto_Pedidocol` VARCHAR(45) NULL,
  PRIMARY KEY (`pedido_idPedido`, `Produto_IdProduto`),
  CONSTRAINT `fk_pedido_has_Produto_pedido1`
    FOREIGN KEY (`pedido_idPedido`)
    REFERENCES `mydb`.`pedido` (`idPedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pedido_has_Produto_Produto1`
    FOREIGN KEY (`Produto_IdProduto`)
    REFERENCES `mydb`.`Produto` (`IdProduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_pedido_has_Produto_Produto1_idx` ON `mydb`.`Relacao_Produto_Pedido` (`Produto_IdProduto` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `fk_pedido_has_Produto_pedido1_idx` ON `mydb`.`Relacao_Produto_Pedido` (`pedido_idPedido` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`TipoCartao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`TipoCartao` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`TipoCartao` (
  `idTipoCartao` INT NOT NULL,
  `Descricao` VARCHAR(45) NULL COMMENT 'Debito, Credito, Alimentacao, Refeicao, Voucher.',
  PRIMARY KEY (`idTipoCartao`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`TipoIdentificao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`TipoIdentificao` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`TipoIdentificao` (
  `idTipoIdentificao` INT NOT NULL,
  `Descricao` VARCHAR(45) NULL,
  PRIMARY KEY (`idTipoIdentificao`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`TipoPagamento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`TipoPagamento` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`TipoPagamento` (
  `idTipoPagamento` INT NOT NULL,
  `Descricao` VARCHAR(45) NOT NULL COMMENT 'A vista, Parcelado com entrada, parcelado sem entrada.',
  PRIMARY KEY (`idTipoPagamento`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`TipoSituacao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`TipoSituacao` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`TipoSituacao` (
  `idTipoSituacao` INT NOT NULL,
  `Descricao` VARCHAR(45) NULL COMMENT 'Entregue, a caminho, Preparando, Devolvido, Em Tentativa.',
  PRIMARY KEY (`idTipoSituacao`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`Tipo_De_Entrega`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Tipo_De_Entrega` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`Tipo_De_Entrega` (
  `idTipo_De_Entrega` INT NOT NULL,
  `Descricao` VARCHAR(100) NULL COMMENT 'Retirada em ponto predeterminado, correios, entregador, fretado, motoboy, bike.',
  `CodigoSeguranca` INT NULL COMMENT 'Codigo de autenticacao pre-definido entre comprador e vendedor, exemplo, quatro ultimos numeros do celular.',
  PRIMARY KEY (`idTipo_De_Entrega`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`Vendedor_Agregado`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Vendedor_Agregado` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`Vendedor_Agregado` (
  `idVendedor Agregado` INT NOT NULL,
  `RazaoSocial` VARCHAR(100) NULL,
  `Local` VARCHAR(200) NULL,
  PRIMARY KEY (`idVendedor Agregado`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`cliente` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`cliente` (
  `IdCliente` INT NOT NULL,
  `Identificacao` VARCHAR(45) NULL,
  `Nome` VARCHAR(100) NOT NULL,
  `Endereco` VARCHAR(200) NULL,
  `IdCarteira` INT NULL COMMENT 'Pode ter mais de uma forma de pagamentos.',
  `TipoIdentificao_idTipoIdentificao` INT NOT NULL,
  PRIMARY KEY (`IdCliente`, `TipoIdentificao_idTipoIdentificao`),
  CONSTRAINT `fk_cliente_TipoIdentificao1`
    FOREIGN KEY (`TipoIdentificao_idTipoIdentificao`)
    REFERENCES `mydb`.`TipoIdentificao` (`idTipoIdentificao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_cliente_TipoIdentificao1_idx` ON `mydb`.`cliente` (`TipoIdentificao_idTipoIdentificao` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`pedido`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`pedido` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`pedido` (
  `idPedido` INT GENERATED ALWAYS AS () VIRTUAL,
  `StatusPedido` VARCHAR(45) NULL,
  `Descricao` VARCHAR(45) NULL,
  `cliente_IdCliente` INT NOT NULL,
  `Frete` FLOAT NULL,
  `Pagamento_idPagamento` INT NOT NULL,
  `Dados_Entrega_idDados_Entrega` INT NOT NULL,
  `Dados_Entrega_Tipo_De_Entrega_idTipo_De_Entrega` INT NOT NULL,
  PRIMARY KEY (`idPedido`, `Pagamento_idPagamento`, `Dados_Entrega_idDados_Entrega`, `Dados_Entrega_Tipo_De_Entrega_idTipo_De_Entrega`),
  CONSTRAINT `fk_pedido_cliente1`
    FOREIGN KEY (`cliente_IdCliente`)
    REFERENCES `mydb`.`cliente` (`IdCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pedido_Pagamento1`
    FOREIGN KEY (`Pagamento_idPagamento`)
    REFERENCES `mydb`.`Pagamento` (`idPagamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pedido_Dados_Entrega1`
    FOREIGN KEY (`Dados_Entrega_idDados_Entrega` , `Dados_Entrega_Tipo_De_Entrega_idTipo_De_Entrega`)
    REFERENCES `mydb`.`Dados_Entrega` (`idDados_Entrega` , `Tipo_De_Entrega_idTipo_De_Entrega`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_pedido_cliente1_idx` ON `mydb`.`pedido` (`cliente_IdCliente` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `fk_pedido_Pagamento1_idx` ON `mydb`.`pedido` (`Pagamento_idPagamento` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `fk_pedido_Dados_Entrega1_idx` ON `mydb`.`pedido` (`Dados_Entrega_idDados_Entrega` ASC, `Dados_Entrega_Tipo_De_Entrega_idTipo_De_Entrega` ASC) VISIBLE;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
